#!/usr/bin/env bash
#
# Registers the ClaudeMonkey native-messaging host with Firefox.
#
# - resolves the `claude` binary and records it in bridge/config.json
# - makes host.js executable
# - installs claudemonkey.bridge.json into Firefox's native-messaging-hosts dir
#
set -euo pipefail

HOST_NAME="claudemonkey.bridge"
EXTENSION_ID="claudemonkey@local"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_JS="$DIR/host.js"

# 1. Resolve the claude binary.
CLAUDE_BIN="${CLAUDEMONKEY_CLAUDE_BIN:-}"
if [ -z "$CLAUDE_BIN" ]; then
  # `claude` is often a shell alias (env -u ANTHROPIC_API_KEY claude); resolve the
  # real executable instead, since the native host won't see shell aliases.
  CLAUDE_BIN="$(command -v claude || true)"
fi
if [ -z "$CLAUDE_BIN" ]; then
  echo "ERROR: could not find the 'claude' CLI on PATH." >&2
  echo "Install Claude Code or set CLAUDEMONKEY_CLAUDE_BIN to its path, then re-run." >&2
  exit 1
fi
# Keep the resolved path as-is (often ~/.local/bin/claude, a stable symlink that
# survives Claude Code version upgrades) rather than pinning a versioned target.
echo "Using claude binary: $CLAUDE_BIN"

# 1b. Optional account profile (CLAUDE_CONFIG_DIR). The native host can't see shell
# aliases that set a custom profile, so we record the profile dir explicitly and host.js
# exports it as CLAUDE_CONFIG_DIR when launching claude. Set CLAUDEMONKEY_CLAUDE_CONFIG_DIR
# (or your current CLAUDE_CONFIG_DIR) to use a non-default profile; leave empty for ~/.claude.
CLAUDE_CONFIG_DIR_VAL="${CLAUDEMONKEY_CLAUDE_CONFIG_DIR:-${CLAUDE_CONFIG_DIR:-}}"
if [ -n "$CLAUDE_CONFIG_DIR_VAL" ]; then
  echo "Using claude config dir: $CLAUDE_CONFIG_DIR_VAL"
fi

# 1c. Environment variables to forward to `claude`. Firefox launches the host from the
# GUI session, where nothing from your shell profile exists — so a credential kept in an
# env var is present in your terminal and missing here, and `claude` reports "Not logged
# in" despite working fine interactively. The names listed below are captured from the
# environment running this script (they must be *exported* to be visible). Add your own:
#   CLAUDEMONKEY_ENV_PASSTHROUGH="FOO,BAR" bash bridge/install.sh
# ANTHROPIC_API_KEY is never forwarded — host.js strips it so generations always bill
# against the subscription.
PASSTHROUGH="${CLAUDEMONKEY_ENV_PASSTHROUGH:-CLAUDE_CODE_OAUTH_TOKEN}"

# 2. Write config.json consumed by host.js. Generated with node (which host.js needs
# anyway) so values with quotes, spaces or backslashes are escaped correctly.
if ! command -v node >/dev/null 2>&1; then
  echo "ERROR: could not find 'node' on PATH; host.js is a Node script and needs it." >&2
  exit 1
fi
CM_BIN="$CLAUDE_BIN" CM_CFG="$CLAUDE_CONFIG_DIR_VAL" CM_PASS="$PASSTHROUGH" node -e '
  const out = { claudeBin: process.env.CM_BIN };
  if (process.env.CM_CFG) out.claudeConfigDir = process.env.CM_CFG;
  const env = {};
  for (const name of (process.env.CM_PASS || "").split(/[\s,]+/).filter(Boolean)) {
    if (name === "ANTHROPIC_API_KEY") continue;
    if (process.env[name]) env[name] = process.env[name];
  }
  const names = Object.keys(env);
  if (names.length) out.env = env;
  require("fs").writeFileSync(process.argv[1], JSON.stringify(out, null, 2) + "\n");
  console.log(names.length
    ? "Forwarding to claude: " + names.join(", ")
    : "No extra env captured (set CLAUDEMONKEY_ENV_PASSTHROUGH=NAME1,NAME2 to forward more)");
' "$DIR/config.json"

# 3. Make host.js executable and generate a launcher that pins an absolute node path.
# host.js starts with `#!/usr/bin/env node`, which resolves against the PATH of whoever
# launched Firefox. A GUI-launched Firefox (Dock, Finder, launchd) has a minimal PATH —
# /usr/bin:/bin:/usr/sbin:/sbin on macOS — so a node from Homebrew, nvm or nix is simply
# absent and the host dies before it can report anything. The launcher removes the
# lookup: the manifest points at it, and it execs the exact node that ran this script.
chmod +x "$HOST_JS"
NODE_BIN="$(command -v node)"
case "$NODE_BIN" in
  /*) ;;
  *) NODE_BIN="$(cd "$(dirname "$NODE_BIN")" && pwd)/$(basename "$NODE_BIN")" ;;
esac
LAUNCHER="$DIR/host-launcher.sh"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by bridge/install.sh — do not edit; re-run the installer instead.
exec "$NODE_BIN" "$HOST_JS" "\$@"
EOF
chmod +x "$LAUNCHER"
echo "Using node: $NODE_BIN"

# 4. Install the native-messaging host manifest.
case "$(uname -s)" in
  Darwin) TARGET_DIR="$HOME/Library/Application Support/Mozilla/NativeMessagingHosts" ;;
  *)      TARGET_DIR="$HOME/.mozilla/native-messaging-hosts" ;;
esac
mkdir -p "$TARGET_DIR"
MANIFEST="$TARGET_DIR/$HOST_NAME.json"
cat > "$MANIFEST" <<EOF
{
  "name": "$HOST_NAME",
  "description": "ClaudeMonkey bridge to the Claude Code CLI",
  "path": "$LAUNCHER",
  "type": "stdio",
  "allowed_extensions": ["$EXTENSION_ID"]
}
EOF

echo "Installed native-messaging host manifest: $MANIFEST"
echo "Done. Reload the ClaudeMonkey extension in Firefox if it was already running."
